### ISSUE TITLE
Questions about esup-otp maintenance & versions

### ISSUE THREAD

**Issue by nothing-fr** [EsupPortail/esup-otp-api#11]
Hi,

Your prerequisites are : **Node v4.* and npm v2**

But those versions are __EOL since [2018](https://github.com/nodejs/release#end-of-life-releases)__.

I've tried to install `esup-otp-api` with the current LTS version of node.js (16.x) on Ubuntu 22.04 and I have a lot of security issues when running `npm install` (a mix of low, moderate, high and critical ones)

- After only `npm install` I have this error : 
```
(node:138127) Warning: Accessing non-existent property 'SYSTEM_INDEX_COLLECTION' of module exports inside circular dependency
/opt/esup-otp-api/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: Cannot read properties of undefined (reading '0')
    at /opt/esup-otp-api/databases/api/mongodb.js:44:17
    at /opt/esup-otp-api/node_modules/mongoose/lib/model.js:4437:16
    at /opt/esup-otp-api/node_modules/mongoose/lib/query.js:3653:9
    at cb (/opt/esup-otp-api/node_modules/mongoose/lib/query.js:1684:14)
    at /opt/esup-otp-api/node_modules/mongodb/lib/utils.js:415:14
    at executeCallback (/opt/esup-otp-api/node_modules/mongodb/lib/utils.js:404:25)
    at handleCallback (/opt/esup-otp-api/node_modules/mongodb/lib/utils.js:128:55)
    at /opt/esup-otp-api/node_modules/mongodb/lib/operations/cursor_ops.js:207:38
    at ClientSession.endSession (/opt/esup-otp-api/node_modules/mongodb-core/lib/sessions.js:129:41)
    at Cursor._endSession (/opt/esup-otp-api/node_modules/mongodb-core/lib/cursor.js:189:13)
    at Cursor._endSession (/opt/esup-otp-api/node_modules/mongodb/lib/cursor.js:226:59)
    at /opt/esup-otp-api/node_modules/mongodb/lib/operations/cursor_ops.js:207:20
    at handleCallback (/opt/esup-otp-api/node_modules/mongodb-core/lib/cursor.js:203:5)
    at /opt/esup-otp-api/node_modules/mongodb-core/lib/cursor.js:608:23
    at queryCallback (/opt/esup-otp-api/node_modules/mongodb-core/lib/cursor.js:248:16)
    at /opt/esup-otp-api/node_modules/mongodb-core/lib/connection/pool.js:532:18
Emitted 'error' event on Function instance at:
    at /opt/esup-otp-api/node_modules/mongoose/lib/model.js:4439:13
    at /opt/esup-otp-api/node_modules/mongoose/lib/query.js:3653:9
    [... lines matching original stack trace ...]
    at /opt/esup-otp-api/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

- `npm audit fix` resolve some of the issues and the API seems to be working.

I have similar problems with `esup-otp-manager`.

 Is the project still supported (latest release is from 2018) ? Do you plan to update to new version of node.js and dependencies  ? What is your advice for new installations (OS versions, security concerns, mongo version...) ?

I didn't find a lot of documentation concerning esup-otp (describing config files options, etc...), is it available somewhere ?

Best regards.

**Comment by mbdeme** [comment]
Hello,

You can use the following versions:
- **node v18.9.0**,

- **npm 8.19.1 and**

- **MongoDB server version: 4.4.16.**
I tested them and it works.

The vulnerabilities present in the package.json file are fixed on the following commit:
https://github.com/EsupPortail/esup-otp-api/commit/0314de6c3982ec737aaba9d2027265e705b005a4

the documentation will be updated soon.

Goodbye
