### ISSUE TITLE
upgrade breaks CORS in sockets.io requests

### ISSUE THREAD

**Issue by prigaux** [EsupPortail/esup-otp-api#12]
In socket.io 1.x, CORS was enabled by default.
Since socket.io 3.x, CORS must be enabled/configured explicitly.

Regression introduced in commit 0314de6c3982ec737aaba9d2027265e705b005a4 "build: upgrade package versions to fix vulnerabilities present in package.json file"

**Comment by vbonamy** [comment]
So since 0314de6, I understand we have to enable/configure explicitly on CAS server explicitly ?
How ? 
Via apache configuration for example on CAS virtualhost ?
```
Header add Access-Control-Allow-Origin "esup-otp-api.univ-ville.fr";
```
would be ok ?
Thank you.

**Comment by prigaux** [comment]
Not on the cas server, it must be done in esup-otp-api to allow to use on cas pages.

**Comment by vbonamy** [comment]
Thank you for PR #13 I merged it.
