### ISSUE TITLE
Authentification sur la connexion à la base MongoDB

### ISSUE THREAD

**Issue by yuyarisalas** [EsupPortail/esup-otp-api#30]
Pas possible de mettre des informations d'authentification sur la connexion à la base MongoDB.

**Comment by floriannari** [comment]
Bonjour,
Dans [address](https://github.com/EsupPortail/esup-otp-api/blob/master/properties/esup.json#L20), vous devriez pouvoir utiliser la syntaxe `username:password@host`

**Comment by yuyarisalas** [comment]
Bonjour, 

Je n'ai pas réussi. Mongoose ne semble pas pouvoir connecter de base mongodb avec authentification... Les URI sont OK car je peux me connecter a mes bases mongodb 
sans problème via mongosh, en remote ou en local. L'erreur est : 

2024-09-24 16:11:50 INFO server/server.js Initializing the api controller 
/home/yuyari/Code/esup-otp/esup-otp-api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:202 
callback(new error_1.MongoServerError(document)); 
^ 

MongoServerError: Authentication failed. 
at Connection.onMessage (/home/yuyari/Code/esup-otp/esup-otp-api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:202:26) 
at MessageStream.<anonymous> (/home/yuyari/Code/esup-otp/esup-otp-api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:61:60) 
at MessageStream.emit (node:events:518:28) 
at processIncomingData (/home/yuyari/Code/esup-otp/esup-otp-api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:124:16) 
at MessageStream._write (/home/yuyari/Code/esup-otp/esup-otp-api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:33:9) 
at writeOrBuffer (node:internal/streams/writable:564:12) 
at _write (node:internal/streams/writable:493:10) 
at Writable.write (node:internal/streams/writable:502:10) 
at Socket.ondata (node:internal/streams/readable:1007:22) 
at Socket.emit (node:events:518:28) { 
ok: 0, 
code: 18, 
codeName: 'AuthenticationFailed', 
connectionGeneration: 0, 
[Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' } 
} 

Avez vous réussi en pratique de connecter une base MongoDB avec auth ? 

Cordialement 

Yuyari SALAS 

= = = = = = = = = = 
Université de Rennes 
Direction du Système d'Information 
Pôle Applications et Services Numériques 


De: "Nari Florian" ***@***.***> 
À: "EsupPortail/esup-otp-api" ***@***.***> 
Cc: "Yuyari Salas" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 18 Septembre 2024 11:23:53 
Objet: Re: [EsupPortail/esup-otp-api] Authentification sur la connexion à la base MongoDB (Issue #30) 





Bonjour, 
Dans [ https://github.com/EsupPortail/esup-otp-api/blob/master/properties/esup.json#L20 | address ] , vous devriez pouvoir utiliser la syntaxe ***@***.***

**Comment by floriannari** [comment]
Bonjour,
> Avez vous réussi en pratique de connecter une base MongoDB avec auth ?

Oui, chez nous nous avons la configuration suivante :
```json
"mongodb": {
	"address": "esup-otp:xxx@localhost",
	"db": "otp",
	"transport": {
		"mail": "mail",
		"sms": "mobile"
	}
},
```
cela génère l'url de connexion mongodb://esup-otp:xxx@localhost/otp
on utilise aussi cette URL pour se connecter via mongosh : `mongosh mongodb://esup-otp:xxx@localhost/otp`

**Comment by yuyarisalas** [comment]
Mon fichier de configuration, qui génère une erreur : 
"mongodb" : { 
"address" : ***@***.***" , 
"db" : "test-otp" , 
"transport" : { 
"mail" : "mail" , 
"sms" : "mobile" 
} 
} 

Par contre ceci fonctionne : 
mongosh ***@***.***/test-otp?authSource=admin 

Sans le ?authSource=admin à la fin ça génère aussi une erreur authentication failed. J'ai essayé de le rajouter dans le code à la fin de l'URI utilisée pour se connecter mais ca génère aussi une erreur. 

Yuyari SALAS 

= = = = = = = = = = 
Université de Rennes 
Direction du Système d'Information 
Pôle Applications et Services Numériques 


De: "Nari Florian" ***@***.***> 
À: "EsupPortail/esup-otp-api" ***@***.***> 
Cc: "Yuyari Salas" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 24 Septembre 2024 17:17:39 
Objet: Re: [EsupPortail/esup-otp-api] Authentification sur la connexion à la base MongoDB (Issue #30) 





Bonjour, 



Avez vous réussi en pratique de connecter une base MongoDB avec auth ? 



Oui, chez nous nous avons la configuration suivante : 
"mongodb" : { "address" : " ***@***.*** " , "db" : " otp " , "transport" : { "mail" : " mail " , "sms" : " mobile " }
}, 


cela génère l'url de connexion ***@***.***/otp 
on utilise aussi cette URL pour se connecter via mongosh : mongosh ***@***.***/otp

**Comment by floriannari** [comment]
Bonjour,
En fait, esup-otp-api concatène "address" et "db"
```js
dbUrl = 'mongodb://' + properties.getEsupProperty('mongodb').address + '/' + properties.getEsupProperty('mongodb').db;
```

Donc dans l'url générée, "test-otp" se retrouve après "?authSource=admin".

Pour éviter ce problème, vous pouvez laisser "db" vide, et tout mettre ("xxx:xxx@xxx.xxx/test-otp?authSource=admin") dans address

**Comment by yuyarisalas** [comment]
"address": ***@***.***/test-otp?authSource=admin" 

Ne fonctionne pas "Invalid database name: 'admin/'" 

Yuyari SALAS 

= = = = = = = = = = 
Université de Rennes 
Direction du Système d'Information 
Pôle Applications et Services Numériques 


De: "Nari Florian" ***@***.***> 
À: "EsupPortail/esup-otp-api" ***@***.***> 
Cc: "Yuyari Salas" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 25 Septembre 2024 10:09:11 
Objet: Re: [EsupPortail/esup-otp-api] Authentification sur la connexion à la base MongoDB (Issue #30) 





Bonjour, 
En fait, esup-otp-api concatène "address" et "db" 
dbUrl = 'mongodb://' + properties . getEsupProperty ( 'mongodb' ) . address + '/' + properties . getEsupProperty ( 'mongodb' ) . db ; 


Donc dans l'url générée, "test-otp" se retrouve après "?authSource=admin". 

Pour éviter ce problème, vous pouvez laisser "db" vide, et tout mettre ("xxx: [ ***@***.*** | ***@***.*** ] /test-otp?authSource=admin") dans address

**Comment by floriannari** [comment]
Une solution de contournement a été trouvée en MP.

Une solution plus propre sera proposée lors de la prochaine mise à jour

**Comment by floriannari** [comment]
Avec la nouvelle version 1.7.0, vous pouvez maintenant laisser "db" vide comme dans l'exemple suivant :
```json
"mongodb": {
    "address": "dbUser:password@mongo.univ.fr/test-otp?authSource=admin",
    "db": "",
    "transport": {
        "mail": "mail",
        "sms": "mobile"
    }
},
```
