### ISSUE TITLE
fix: The registration token is not a valid FCM registration token

### ISSUE THREAD

**Issue by floriannari** [EsupPortail/esup-otp-api#33]
ne pas activer push si le gcm_id a pour valeur "undefined"
par exemple: POST /users/uid/methods/push/activate/644299/undefined/iOS/Apple/iPhone14,7

et au moment d'envoyer une notification, si on se rend compte que gcm_id == "undefined", désactiver la méthode

**Comment by floriannari** [comment]
édit : en cas de gcm_id "undefined", se comporter comme si les notifications étaient désactivées (https://github.com/EsupPortail/esup-otp-api/blob/master/properties/esup.json#L94 à false)

**Comment by aanli** [comment]
Si pending à true (cf. https://github.com/EsupPortail/esup-otp-api/blob/master/properties/esup.json#L95),
on devrait activer la méthode push même si le gcm_id est "undefined". Ainsi, l'utilisateur pourra utiliser la méthode push même s'il ne peut pas recevoir de notification
