### ISSUE TITLE
Exception EsupOtpBypassProvider

### ISSUE THREAD

**Issue by YoECN** [EsupPortail/esup-otp-api#39]
Bonjour,

Lorsque la brique ESUP OTP API est injoignable depuis le serveur CAS, quelle que soit la raison (arrêt programmé, plantage, etc.), l'accès à une application web où l'authentification renforcée est exigée se fait alors sans second facteur. L'erreur qui suit apparaît dans les logs du CAS :

ERROR [org.esupportail.cas.config.support.authentication.EsupOtpBypassProvider] - <Exception ...>

Ce comportement par défaut participe à maximiser la disponibilité des applications web. Si l'on souhaitait au contraire maximiser la sécurité en bloquant les accès tant que ESUP OTP API n'est pas fonctionnel, comment faudrait-il s'y prendre ? Je ne vois pas de paramétrage côté APEREO CAS. Cela passerait-il par une évolution du module CAS esupotp ?

Merci,
Yoann J.

**Comment by floriannari** [comment]
Bonjour,
Merci pour ce retour.
Je viens de créer une issue sur le dépôt git d'esup-otp-cas https://github.com/EsupPortail/esup-otp-cas/issues/16

**Comment by floriannari** [comment]
@YoECN en attendant que ce soit implémenté, vous pouvez surcharger EsupOtpBypassProvider.java (comme le permet CAS Overlay), et remplacer `return false;` par `return true;` dans le `catch (Exception e)`
https://github.com/EsupPortail/esup-otp-cas/blob/master/src/main/java/org/esupportail/cas/config/support/authentication/EsupOtpBypassProvider.java#L62

**Comment by YoECN** [comment]
@floriannari, c'est parfait, merci !
