### ISSUE TITLE
Méthode Push

### ISSUE THREAD

**Issue by YoECN** [EsupPortail/esup-otp-api#41]
Bonjour,

Il me semble avoir lu quelque part qu'il n'était plus nécessaire d'avoir des clés d'API Google pour faire fonctionner le mode Push. Seulement, je ne retrouve pas l'info. Je me dis qu'en ouvrant une "issue", l'information sera mieux diffusée dans la communauté. 

De mon côté, en configuration standard d'ESUP-OTP-API, impossible de faire fonctionner l'application mobile ESUP AUTH. Je sais que des collègues d'autres établissements utilisent l'application mobile avec succès et ont pu obtenir des paramètres de configuration en formulant une demande à l'URL :  https://www.esup-portail.org/content/contact
(chose que j'avais faite également, sans succès).

Merci de votre éclairage à ce sujet,
Yoann

**Comment by floriannari** [comment]
Bonjour,
Effectivement, @aanli a implémenté cette fonctionnalité en début d'année.
Pour cela, il suffit de mettre "notification" à false et de laisser "pending" à true https://github.com/EsupPortail/esup-otp-api/blob/master/properties/esup.json#L94

L'utilisateur ne recevra pas de notification, mais devra ouvrir l'application sur son smartphone.


Concernant la demande à https://www.esup-portail.org/content/contact , on va peut-être changer la procédure car vous n'êtes pas la première personne pour qui la demande n'arrive pas jusqu'à nous.
En attendant, je vous invite à m'envoyer un message via RocketChat => https://rocket.esup-portail.org/direct/florian.nari

**Comment by YoECN** [comment]
Bonjour,

J'ai intégré les éléments de paramétrage de la méthode Push, merci encore ! Lors des tests, côté utilisateur, la page CAS "en attente de la validation par téléphone" s'affiche suivie de "afficher les autres méthodes" après authentification LDAP. Côté mobile, aucune notification à ce stade ce qui paraît déjà anormal.

Il faut que je clique explicitement sur "afficher les autres méthodes" puis "Application téléphonique" pour que la notification apparaisse sur le mobile. 

En cas d'acceptation de la connexion sur le téléphone, voici ce qui est journalisé sur le serveur ESUP OTP API : 

DEBUG GET /users/####/methods/push/#####
DEBUG POST /users/####/methods/push/#####
DEBUG accept_authentication ? ###### VS #######
DEBUG accept_authentication OK : lt = #######
DEBUG sockets.emitCas OK : otp = ######

Le code OTP est bien généré mais n'est pas renseigné automatiquement dans la page du CAS. Si je le renseigne manuellement, c'est OK. 

Aucun blocage de flux dans les logs (firewalls, reverses-proxies, instances apache...) ou toute autre erreur pouvant expliquer ce comportement. Les autres méthodes comme TOTP, Webauthn, fonctionnent, elles, sans difficulté. Je soupçonne la websocket mais je ne vois pas trop comme déboguer la situation. Une idée ? 

Merci,
Yoann

**Comment by YoECN** [comment]
Mea culpa, c'est réglé !

C'était une histoire de socket qui ne s'établissait côté navigateur client. Mauvais paramétrage dans le serveur CAS. Dans le fichier cas.properties, l'instruction "cas.http-web-request.header.content-security-policy" pointait vers l'instance ESUP OTP API de tests et non de production. Le navigateur n'établissait alors pas la socket pour des raisons de sécurité.

cas.http-web-request.header.content-security-policy=script-src 'self' 'unsafe-inline' 'unsafe-eval' <###SRV ESUP-OTP-API####>; object-src 'none'; worker-src 'self' blob: 'unsafe-inline'

Merci pour le coup de main et belles fêtes de fin d'année,
Yoann

**Comment by aanli** [comment]
Bonjour,

Pour obtenir les clés pour le push,
c'est bien la bonne procédure de passer par https://www.esup-portail.org/content/contact
Il faut mettre dans l'objet : "ESUP AUTH:  serviceAccount".
Ne pas hésiter à préciser dans le message que c'est pour l'obtention de la clé de service pour les notifications mobile avec Esup Auth.  (on va le préciser dans le fichier de config).
La réponse peut prendre 2 ou 3 jours voire plus en fonction de la période (vacances, ...).

Aymar
